### ISSUE TITLE
invalid pure specifier (only '= 0' is allowed) before '(' token

### ISSUE THREAD

**Issue by capcarneiro** [Hotaman/OneWireSpark#16]
Veryfing code using this library in Particle Build fails with this error:

```
OneWire/OneWire.h:93:42: error: invalid pure specifier (only '= 0' is allowed) before '(' token
     STM32_Pin_Info* PIN_MAP = HAL_Pin_Map()
```

**Comment by Hotaman** [comment]
I will try to duplicate this error and let you know what I find in a day or two. I haven't used Build since I last updated this lib. I've been using Dev. I'm updating my weather station code this week so if there is a problem, I will get it fixed.

**Comment by Hotaman** [comment]
In discussion with Particle, they informed me that there are some major changes coming that will effect low level libraries. Since this has become such a popular lib and it is tied very closely to the low level  firmware, I have handed it over to Particle and they have made it an Official library. This will allow it to be updated before new firmware is released rather than after which should make a lot of folks (including me) happy!
