### ISSUE TITLE
Feature Request: Move to new low level IO pin operations

### ISSUE THREAD

**Issue by LukeUSMC** [Hotaman/OneWireSpark#17]
I maintain a DS18B20 lib for particle users and the new lib manager will allow for dependancies so I will no longer include a copy of your lib in mine.  I was asked by some of the elites to migrate to the new low level IO functions instead of the pinmap method that has been used for so long.  I am happy to complete this work but I need some guidance on a few things.
[Low Leve Input/Output - Particle Docs](https://docs.particle.io/reference/firmware/photon/#low-level-input-output)
Example from reset()

``` cpp
digitalWriteFast(_pin, LOW);
    pinModeFastOutput();   // drive output low
```

I have moved from digitalWriteFastLow to digitalWriteFast but the command after that is where I am confused.  This is common in most functions and I am sure needed but I can't determine what it is doing besides setting the pin to output but wouldn't digitalWriteFast already have the pin in output mode?  It says "drive output low" in the comments but the prior command will do the same.  Please advise and I am happy to submit a PR if/when I get it all working.  Thanks.

**Comment by Hotaman** [comment]
Luke,
Glad to hear your still working on your 1820 support. You mention moving to the 'new' low level IO functions. Are these 'new' function different than the current digital____fast() functions?
I haven't seen anything newer than what I am using now, can you clarify?

As far as the purpose for the pinModeFastOut/Input() functions:

The Fast IO functions are 'fast' because they don't do anything else, like set the pin to output when you do a write. When building a software protocol, this is what you need to do it correctly.

From the Particle Docs:
"In order to provide the fastest possible bit-oriented I/O, the normal safety checks must be skipped. As such, please be aware that the programmer is responsible for proper planning and use of the low level I/O functions.**Prior to using the following low-level functions, pinMode() must be used to configure the target pin**."

For a OneWire interface, the bus drivers are normally open collector. I simulate an open collector output using a totem pole output by changing the pin direction rather than the pin state.

With a pull-up on the pin and the pin state set to LOW:

Setting the pin to input = HIGH output or Input from the device
Setting the pin to output = LOW output.

If the OneWire lib needs updating, this is a good time for me to do it as I am finalizing my Weather Station code this week which of course uses OneWire for several devices. It will be trivial for me to make updates if required, but I don't see anything new in the docs.

**Comment by LukeUSMC** [comment]
From what I see in the lib the HAL_Pin_Mode is used which is good because all platforms (including bluz, oak) have implemented this abstraction layer so those are good to stay. The digital____Fast/Low/High do have new API "official" equivalents. This was requested by Scruffr but I see what he is talking about. The link to docs I sent before should uncover the following functions: 
pinSetFast - Goes High
digitalWriteFast - calls pinSet/Reset under the covers (I think we don't need this)
pinResetFast- Goes Low
pinReadFast - Reads high/low

Looking at these functions and the lib I thought (totally defer to you of course) that the "unofficial" pinmap could be pulled and new functions replace existing as follows:
digitalWriteFastLow to pinResetFast
digitalWriteFastHigh to pinSetFast
pinModeFastxxxx stays the same
digitalReadFast to pinReadFast

That would eliminate all of the platform statements from the header and be more user friendly for those of us without your understanding of pinMaps and keeps us all in the official API. I have a fork that I've implemented those changes on and can test on a Photon, Core, Bluz and electron. It's your lib so if I'm off base I'm all ears. Thanks again for contributing to the community and making things approachable for us newbies to OneWire and MCUs in general.

**Comment by Hotaman** [comment]
OK I see what is desired. I need to move some code from the gutter up to the curb. This probably has something to do with the reported error in build that I'm going to look at as well.

I'll swap out the functions and hook it up to the scope. I need to see how the new API fast functions behave. I should probably pull the latest firmware source to see if they compile inline or not, might need to make some tweaks here and there.

Yes my fastPinMode functions will need to stay until they include them in the API as well. They are just as important as the bit Set and Reset functions for this lib. I'll switch to digitalWriteFast to avoid the extra JSR to it that Set and Reset use. I'm thinking none of these are compiled in-line which may cause some timing problems. I'll let you know what I figure out.

I agree getting rid of the platform specific code will help understanding and maintainability. I will test particle devices, I don't have bluz or redbear devices yet.

Thanks Luke

**Comment by LukeUSMC** [comment]
Thank you! Let me know if you need any help from me. Just throw me something to test when you are ready for Bluz. I don't have readbear either but I'm sure someone will pick it up. 

BTW, I know there are pending updates for the libs system, some of the elites are testing things, to be more like arduino lib system so while you are in there you may want to check with someone at Particle to see there are details on that.  I'm updating mine to also take advantage of the new 6.0 logging feature (check /docs/reference/firmware.md in firmware repo if interested) so users can opt into different levels of debugging/info.

**Comment by LukeUSMC** [comment]
One last thing. I have some BluzDKs and a Gateway module I'm happy to ship to you if you want some. They were a gift from Eric at Bluz for Beta and some minor lib tweaks for NRF. I don't think I'll ever use all that I have. You are welcome to them if you want them.

**Comment by Hotaman** [comment]
Hey Luke, they still have not added a fastPinMode() to the firmware so there really isn't anyway to remove _all_ the platform specifics from the lib so there really isn't a point to change it yet. Particle has indicated to me that there are some major changes coming to the firmware that will effect low level libs like OneWire. I have handed this lib over to Particle and they have made it an official lib and will be maintaining it from here on out so you should be good to go.

Thanks for the hardware offer, I'll pass at this time since I'm unto my armpits in a large automation project. We will be introducing it next spring so I'm not planning to have much spare time between now and then.
