### ISSUE TITLE
'INPUT' was not declared in this scope

### ISSUE THREAD

**Issue by e-coucou** [Hotaman/OneWireSpark#7]
Veryfing code using this library in Particle Build fails with this error:
```
OneWire/OneWire.cpp:135:15: error: 'INPUT' was not declared in this scope
  pinMode(pin, INPUT)

**Comment by chucku** [comment]
Problem still there.  Since this is avery popular library I suspect I am doing something wrong!

**Comment by jenesaisdiq** [comment]
Nope @chucku, this library just hasn't been updated to work with the Photon. I'll see what I can do about fixing it and putting in a PR.

**Comment by Andre-Joosten** [comment]
How is this looking, I see the problem is still there..

**Comment by jenesaisdiq** [comment]
Hey @Andre-Joosten I've put up a gist that works, but it's using a trick that the next firmware update is going to break. Need to find another work-around. You can grab it from here and see if it works for you... compiles and runs with consistent values for me on both Cores and Photons, but haven't had a good way to determine why my returned values (from a temperature sensor) are crappy. I suspect that it's the temp sensor code and that the OneWire's working fine.

https://gist.github.com/jenesaisdiq/5a1a151d16e4eeaf0e69

**Comment by Andre-Joosten** [comment]
Sorry for having to ask, how to you link that via the Web ide.
I.e. how do I get access to https://gist.github.com/jenesaisdiq/5a1a151d16e4eeaf0e69 via the Web IDE

**Comment by jenesaisdiq** [comment]
Isn't the most straightforward thing, you may want to wait until it's up normally. That caution said, here's the steps I'd follow:

1. Click the Code '<>' icon in the toolbar. Remove the OneWire you probably already have included. Here's a screenshot where I have 'RELAYSHIELD' included. https://www.dropbox.com/s/ijxz41cae2doo1x/Screenshot%202015-07-26%2016.11.16.png?dl=0

2. Click the '+' icon in the upper right to add files to this project.

3. Name one of them OneWire, and it should rename the other one too. This'll give you OneWire.cpp and OneWire.h

4. Copy/paste the code from the two files my gist to their identically-named files in your project.

5. Figure out why you have a compile error. I'm betting you'll need to delete the line '#include "OneWire/OneWire.h"'

6. Rock out like some kinda benevolent genie granted you a wish and it actually worked the way you wanted.

**Comment by jenesaisdiq** [comment]
Hey @Hotaman, would you like us (Particle) to create an official OneWire library and start maintaining it? Would take the burden of keeping up with our changes off you.

**Comment by Andre-Joosten** [comment]
Thanks for that, got that more or less to go.
But i see the problem you are up against. Is there any documentation for the Core VS Photon defines?

**Comment by jenesaisdiq** [comment]
Great. There isn't a good doc on porting code from Core to Photon right now, but this has become enough of a need that it's floated up onto my radar- I'm VP of Product. Planning to write one this week and contact the top 10+ library owners about upgrade path. Generally speaking there's only a couple of areas where you run into conflicts, and they're all low-level calls.

**Comment by matteocontrini** [comment]
@Hotaman can you update the repo with the corrected code with Photon support?
Also, @jenesaisdiq is that documentation public?

**Comment by jenesaisdiq** [comment]
Hey @matteocontrini funny seeing you here too! Same gist as over in Dallas Temp: https://gist.github.com/jenesaisdiq/5a1a151d16e4eeaf0e69

This has been updated to work with the (soon to come) firmware update that I was concerned about breaking it. Last couple of weeks have been jammed up with other work, so sorry to leave you hanging.

I've really only seen people run into `PIN_MAP` problems because of an impending name collision with the yet-unreleased new system firmware. The fix is pretty simple, just making `PIN_MAP` into `PIN_MAP2`. For OneWire I've also updated the port to be correct for Photons. You can see the changes in this block of code:
```
#if PLATFORM_ID == 0 // Core
  #define pinLO(_pin) (PIN_MAP[_pin].gpio_peripheral->BRR = PIN_MAP[_pin].gpio_pin)
  #define pinHI(_pin) (PIN_MAP[_pin].gpio_peripheral->BSRR = PIN_MAP[_pin].gpio_pin)
#elif PLATFORM_ID == 6 // Photon
  //#include "pinmap_impl.h"
  //#undef PIN_MAP
  STM32_Pin_Info* PIN_MAP2 = HAL_Pin_Map(); // Pointer required for highest access speed
  #define pinLO(_pin) (PIN_MAP2[_pin].gpio_peripheral->BSRRH = PIN_MAP2[_pin].gpio_pin)
  #define pinHI(_pin) (PIN_MAP2[_pin].gpio_peripheral->BSRRL = PIN_MAP2[_pin].gpio_pin)
#else
  #error "*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***"
#endif
// fast pin access
#define pinSet(_pin, _hilo) (_hilo ? pinHI(_pin) : pinLO(_pin))
```
and this block of code, which occurs in a couple of places and versions:
```
    #if PLATFORM_ID == 6
        HAL_Pin_Mode(_pin, OUTPUT);
    #else
        pinMode(_pin, OUTPUT);
    #endif
```

It's really useful to know about `#if PLATFORM_ID==6` or `0` for creating different behaviors on Cores (0) and Photons (6).

But like I said over in https://github.com/tomdeboer/SparkCoreDallasTemperature/issues/2, give it a go and let me know if your data looks good.

**Comment by matteocontrini** [comment]
@jenesaisdiq :smile: yes it's always me. I'd really like to see the two repositories collaborate together to make an "universal" library for OneWire sensors!
Anyway thank you for the contributions and for posting the two gists. I will check them

**Comment by kyleoliveira** [comment]
@jenesaisdiq Did the Particle team ever end up taking over maintenance of an "official" OneWire implementation as you offered above?

**Comment by Hotaman** [comment]
I traded some emails with them and for now I'll maintain this lib. I'll be digging back into this lib after Halloween. My next big 1-wire project is aimed at the Electron so it keeps getting pushed back with the Electron. I'm making some changes this weekend for the lucky dogs that have them now adding the new platform ID. This lib will be working on the Electron when the rest of us get them.

BTW - This lib is a general purpose lib supporting any 1-wire device, sensor or otherwise. I use a lot of the non-sensor 1-wire devices and the advanced devices (i.e. event tracker, remember the Java iButton? Ya I have one!)

**Comment by Hotaman** [comment]
will be fully updated and tested on all platforms in the next day or two. I have it working great on the Electron now as well.
